language: java
jdk: oraclejdk8
script: ant main
notifications:
  email: false
  slack:
    rooms:
      - secure: osYsDKjgXfbZ9XMktHJzzxfbqRqPQPgDy66ISOoQTxZD9m9ASkr5XX4YiSYrBBIDvNp9Jg6Vvl0EjtS0NuGUOz+MTQLa4ozUgzacn+OCtf4Sh5HWOiQRmunHIoo0RkmFAl1b+Mrasma+u+SPPCz6vAuu8hhxu3SkkqJ0vmjxwaBtteZSJYpnljCgNkxqjoqfzorhjkpRRtHAJoZRg9mATMGOepw8nN3eYlKIM5uF5AxZ/xDizP+1YFohywQRvYkQwddmD4xFAw78CAp/twKBong+JPVzEFCKgOyXyfnGjT8eHU61vJnynfYvZahigFdf21/J8o92fkNUT4R3mfna35qQ14wkAhg6YHCwIou5cqmBrX5UHMJowmHVGruvJFWABkIVya8xpvu1zY7jwLbNDgvuuaWO0x+pMhlqCPBH5WQ5grRj4K0Uw5M3ulkUJb5kIEnzB3I6jEZUdT3ZlULkdT0O3E47xjfB0tTRhzWUzlDfV6AMSLIr6s7d+HlLKVd/pxGpXr8Yqol+AN9OG0TAyjnUDHUPA12dHl50zjA/aNG0Ke3lcMV0fYNCV9mid2IFFa5zlg0dDNAc0NVw7M68fWuXetrd40nmATBE6SpkrpmiOW+7esROTpKzR5MmB/IngZ7wykFl/NZt0BaCwN01j2h+2Fkh+SdDkKPaLBxSpGc=
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
