language: java
jdk: oraclejdk8
script: ant main
notifications:
  slack:
    on_success: change
    secure: hWvp7LLH9qMEeM+KduyXNddCs63qL+hG4TC9Bz3t+tfUJGu5oPwd66M+aevWy3IebMmXgkOJ7xDoFz2d+6D/IEFpw5fq0GXrl+I4K2Lh4qAtQmBFBU6DXgzTV3AJ9iqOefiExkm552e5qv0sJ55NhSVwd1h6F8F+Zwrm8ZWapK1u1RcFn4taNZTW8e/NuBdq1fjmG7ZNG8XSvr7WDHEMBRWo+xbwwCr0kTSGeZgJNpZ/3SQFvMnI9dHlwvAdwfmMIW7SmhXaM3YVr5JJjIhPga2pc8FuBTl9YuBmrxxqJpjK2r3ylhm0Sy3PRWIAdeWDSyDm18CY53JXqn2wxgB0Rga61u11MJ9Q6O1Xzp+5fOfapM4BvnlrG7kj10bGFaz6hV5i0bsiFa/PvSAKi4plQYG9tPKoLfUHjjv2k1OAJSQIgDbNEKwc2oAaPj+ryTijE93GFnudD2rjN7U/2fB1IKZrfB1hhE+PYb3Ex9erUUoZCC797jpShOhSGhxrM5aHoX+bDxtcCM7c81Q+d/YD+YzfqEiia3Pv408eP2JQfijEX9eZZcFGebDfctKPR9wAFDaTqcNy7WwDatNLKxW2AjkN+WvoE9/zcefNUkrpSGfQFYFVkyyQR5XUXKxKl63kaa3MQ/jiR4KKh1Naa4gp4471UmSA6v8lPovf1rY3ffE=
