language: java
jdk: oraclejdk8
script: ant main
notifications:
  email: false
  slack:
    rooms:
      - secure: Aa1+dPsrhMj1SqitO87xeGX9S7ev5lZZgaBWd/rAI2gknf16nVNtr3CRurXJRCe4ZIs4oy34K99pJSpZiHzUkvyQlaj1/EPE3UNAjmBgy9JMDxpJznH85OzClJocbv/as9qOaexS1zunHvXPOLLJvLZKfzRAENKOcwJzCv4InECcD4txp8W830vIRxTchcQBbRvST03nLc8aSUGlpjvl+ZK+i81Nx//WINehsl/2KUgpR6uXnI3c8TKEeKOVzC1RkGO87RNidoFa8cA8pzyv5wjrkBrXatPjD1pStLDapDLXPjWoOT2BRHNKkwtxRkFO48Swl/fTpzDIvM0jK1P6uqqPCCpFWaI5KTtxzYA35Eh6r3Ee9QmuB6YNnml1Z44vwW/lJHUtH0OMN1p+aL3eRVcHm/EDpAYsCL1NoDX19YG5d/QuvRLIj9ZiDWbcxG/TVJ9HRjZ93PZSVbEjUZI6VnqiS/hZGG7EsZdfT8a0gVDaMgAdepe6h4O7yVXY9puJbmuo1J/7su1xRNEuytxPqvPPkhtLGYTotUPjccWJOsRX66L0UhwoEeikpKvN2jNwyxXSS5xOeu2mozH0tmehMSY0kT2TX0qSrJCbEb1VooGkmcehYyz6jloXu7fUJGIYNvztWH1o4oIZqrbPcv2wqsgP0deKRO7DB29ZyB3Bup0=
    on_success: always
    on_failure: always
    template:
    - Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
      for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.
    - 'Execution time: *%{duration}*'
    - 'Message: %{message}'
